/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package swing.Employee;

/**
 *
 * @author cereal
 */
public class DiscountTypePopup extends javax.swing.JDialog {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DiscountTypePopup.class.getName());

	/**
	 * Creates new form DiscountTypePopup
	 */
	public DiscountTypePopup(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                DiscountTypePanel = new javax.swing.JPanel();
                DiscountTypeLabel = new javax.swing.JLabel();
                DiscountTypeCheckboxPanel = new javax.swing.JPanel();
                SeniorPWD = new javax.swing.JCheckBox();
                BulkDiscount = new javax.swing.JCheckBox();
                PromoCode = new javax.swing.JCheckBox();
                DiscountTypeExitBtn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                DiscountTypePanel.setBackground(new java.awt.Color(0, 153, 153));

                DiscountTypeLabel.setText("Discount type");

                SeniorPWD.setText("Senior / PWD");

                BulkDiscount.setText("BulkDiscount");
                BulkDiscount.addActionListener(this::BulkDiscountActionPerformed);

                PromoCode.setText("Promo Code (SALE20)");

                javax.swing.GroupLayout DiscountTypeCheckboxPanelLayout = new javax.swing.GroupLayout(DiscountTypeCheckboxPanel);
                DiscountTypeCheckboxPanel.setLayout(DiscountTypeCheckboxPanelLayout);
                DiscountTypeCheckboxPanelLayout.setHorizontalGroup(
                        DiscountTypeCheckboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountTypeCheckboxPanelLayout.createSequentialGroup()
                                .addContainerGap(58, Short.MAX_VALUE)
                                .addGroup(DiscountTypeCheckboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(SeniorPWD)
                                        .addComponent(BulkDiscount)
                                        .addComponent(PromoCode))
                                .addGap(51, 51, 51))
                );
                DiscountTypeCheckboxPanelLayout.setVerticalGroup(
                        DiscountTypeCheckboxPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountTypeCheckboxPanelLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(SeniorPWD)
                                .addGap(18, 18, 18)
                                .addComponent(PromoCode)
                                .addGap(18, 18, 18)
                                .addComponent(BulkDiscount)
                                .addContainerGap(36, Short.MAX_VALUE))
                );

                DiscountTypeExitBtn.setText("Exit");
                DiscountTypeExitBtn.addActionListener(this::DiscountTypeExitBtnActionPerformed);

                javax.swing.GroupLayout DiscountTypePanelLayout = new javax.swing.GroupLayout(DiscountTypePanel);
                DiscountTypePanel.setLayout(DiscountTypePanelLayout);
                DiscountTypePanelLayout.setHorizontalGroup(
                        DiscountTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DiscountTypePanelLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(DiscountTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountTypePanelLayout.createSequentialGroup()
                                                .addComponent(DiscountTypeCheckboxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountTypePanelLayout.createSequentialGroup()
                                                .addComponent(DiscountTypeExitBtn)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DiscountTypePanelLayout.createSequentialGroup()
                                                .addComponent(DiscountTypeLabel)
                                                .addGap(87, 87, 87))))
                );
                DiscountTypePanelLayout.setVerticalGroup(
                        DiscountTypePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DiscountTypePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(DiscountTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DiscountTypeCheckboxPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DiscountTypeExitBtn)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DiscountTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(DiscountTypePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void BulkDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BulkDiscountActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_BulkDiscountActionPerformed

        private void DiscountTypeExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiscountTypeExitBtnActionPerformed
                // TODO add your handling code here:
		dispose();
        }//GEN-LAST:event_DiscountTypeExitBtnActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				DiscountTypePopup dialog = new DiscountTypePopup(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JCheckBox BulkDiscount;
        private javax.swing.JPanel DiscountTypeCheckboxPanel;
        private javax.swing.JButton DiscountTypeExitBtn;
        private javax.swing.JLabel DiscountTypeLabel;
        private javax.swing.JPanel DiscountTypePanel;
        private javax.swing.JCheckBox PromoCode;
        private javax.swing.JCheckBox SeniorPWD;
        // End of variables declaration//GEN-END:variables
}
