/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Employee;
import swing.AdminLogin;


/**
 *
 * @author macbookpro
 */
public class EmployeeCheckout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeCheckout.class.getName());

    /**
     * Creates new form EmployeeCheckout
     */
    public EmployeeCheckout() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEmployeeCheckout = new javax.swing.JPanel();
        EmployeeCheckoutSelectiohPanel = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JButton();
        ProductsBtn = new javax.swing.JButton();
        ChangeAccountBtn = new javax.swing.JButton();
        PowerOffBtn = new javax.swing.JButton();
        EmployeeCheckoutPanel = new javax.swing.JPanel();
        CheckoutBtn = new javax.swing.JButton();
        EmpCheckoutNameField = new javax.swing.JTextField();
        EmpCheckoutPriceField = new javax.swing.JTextField();
        EmpCheckoutDiscountPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        EmpCheckoutBtn1 = new javax.swing.JButton();
        EmpCheckoutBtn2 = new javax.swing.JButton();
        EmpCheckoutBtn3 = new javax.swing.JButton();
        EmpCheckoutBtn4 = new javax.swing.JButton();
        EmpCheckoutBtn5 = new javax.swing.JButton();
        EmpCheckoutBtn6 = new javax.swing.JButton();
        EmpCheckoutBtn7 = new javax.swing.JButton();
        EmpCheckoutBtn8 = new javax.swing.JButton();
        EmpCheckoutBtn9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        PanelEmployeeCheckout.setBackground(new java.awt.Color(29, 81, 160));
        PanelEmployeeCheckout.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        EmployeeCheckoutSelectiohPanel.setBackground(new java.awt.Color(0, 153, 153));

        HomeBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ProductsBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        ProductsBtn.setText("Products");
        ProductsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ChangeAccountBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        ChangeAccountBtn.setText("Change Account");
        ChangeAccountBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ChangeAccountBtn.addActionListener(this::ChangeAccountBtnActionPerformed);

        PowerOffBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        PowerOffBtn.setText("Power OFF");
        PowerOffBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout EmployeeCheckoutSelectiohPanelLayout = new javax.swing.GroupLayout(EmployeeCheckoutSelectiohPanel);
        EmployeeCheckoutSelectiohPanel.setLayout(EmployeeCheckoutSelectiohPanelLayout);
        EmployeeCheckoutSelectiohPanelLayout.setHorizontalGroup(
            EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCheckoutSelectiohPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        EmployeeCheckoutSelectiohPanelLayout.setVerticalGroup(
            EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCheckoutSelectiohPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        EmployeeCheckoutPanel.setBackground(new java.awt.Color(0, 153, 153));
        EmployeeCheckoutPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CheckoutBtn.setBackground(new java.awt.Color(0, 204, 51));
        CheckoutBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        CheckoutBtn.setText("CHECK OUT");
        CheckoutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        EmpCheckoutNameField.setEditable(false);
        EmpCheckoutNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        EmpCheckoutNameField.addActionListener(this::EmpCheckoutNameFieldActionPerformed);

        EmpCheckoutPriceField.setEditable(false);
        EmpCheckoutPriceField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        EmpCheckoutPriceField.addActionListener(this::EmpCheckoutPriceFieldActionPerformed);

        EmpCheckoutDiscountPanel.setBackground(new java.awt.Color(204, 204, 204));
        EmpCheckoutDiscountPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jLabel1.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        jLabel1.setText("Discount");

        jCheckBox1.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        jCheckBox1.setText("Senior / PWD");

        jCheckBox2.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        jCheckBox2.setText("Loyalty Points");

        javax.swing.GroupLayout EmpCheckoutDiscountPanelLayout = new javax.swing.GroupLayout(EmpCheckoutDiscountPanel);
        EmpCheckoutDiscountPanel.setLayout(EmpCheckoutDiscountPanelLayout);
        EmpCheckoutDiscountPanelLayout.setHorizontalGroup(
            EmpCheckoutDiscountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpCheckoutDiscountPanelLayout.createSequentialGroup()
                .addGroup(EmpCheckoutDiscountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmpCheckoutDiscountPanelLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(EmpCheckoutDiscountPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(EmpCheckoutDiscountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1))))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        EmpCheckoutDiscountPanelLayout.setVerticalGroup(
            EmpCheckoutDiscountPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmpCheckoutDiscountPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout EmployeeCheckoutPanelLayout = new javax.swing.GroupLayout(EmployeeCheckoutPanel);
        EmployeeCheckoutPanel.setLayout(EmployeeCheckoutPanelLayout);
        EmployeeCheckoutPanelLayout.setHorizontalGroup(
            EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCheckoutPanelLayout.createSequentialGroup()
                .addGroup(EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(EmpCheckoutPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(EmployeeCheckoutPanelLayout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(CheckoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(EmployeeCheckoutPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(EmpCheckoutDiscountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(EmployeeCheckoutPanelLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(EmpCheckoutNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        EmployeeCheckoutPanelLayout.setVerticalGroup(
            EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeCheckoutPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(EmpCheckoutNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmpCheckoutPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EmpCheckoutDiscountPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CheckoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout PanelEmployeeCheckoutLayout = new javax.swing.GroupLayout(PanelEmployeeCheckout);
        PanelEmployeeCheckout.setLayout(PanelEmployeeCheckoutLayout);
        PanelEmployeeCheckoutLayout.setHorizontalGroup(
            PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmployeeCheckoutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(EmployeeCheckoutSelectiohPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmpCheckoutBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpCheckoutBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpCheckoutBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(EmpCheckoutBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpCheckoutBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmpCheckoutBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmpCheckoutBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpCheckoutBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmpCheckoutBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(EmployeeCheckoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelEmployeeCheckoutLayout.setVerticalGroup(
            PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelEmployeeCheckoutLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PanelEmployeeCheckoutLayout.createSequentialGroup()
                        .addComponent(EmployeeCheckoutSelectiohPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelEmployeeCheckoutLayout.createSequentialGroup()
                        .addComponent(EmployeeCheckoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(PanelEmployeeCheckoutLayout.createSequentialGroup()
                        .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpCheckoutBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpCheckoutBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpCheckoutBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpCheckoutBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpCheckoutBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpCheckoutBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(EmpCheckoutBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpCheckoutBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmpCheckoutBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEmployeeCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEmployeeCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeAccountBtnActionPerformed
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangeAccountBtnActionPerformed

    private void EmpCheckoutNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCheckoutNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpCheckoutNameFieldActionPerformed

    private void EmpCheckoutPriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpCheckoutPriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpCheckoutPriceFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeCheckout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeAccountBtn;
    private javax.swing.JButton CheckoutBtn;
    private javax.swing.JButton EmpCheckoutBtn1;
    private javax.swing.JButton EmpCheckoutBtn2;
    private javax.swing.JButton EmpCheckoutBtn3;
    private javax.swing.JButton EmpCheckoutBtn4;
    private javax.swing.JButton EmpCheckoutBtn5;
    private javax.swing.JButton EmpCheckoutBtn6;
    private javax.swing.JButton EmpCheckoutBtn7;
    private javax.swing.JButton EmpCheckoutBtn8;
    private javax.swing.JButton EmpCheckoutBtn9;
    private javax.swing.JPanel EmpCheckoutDiscountPanel;
    private javax.swing.JTextField EmpCheckoutNameField;
    private javax.swing.JTextField EmpCheckoutPriceField;
    private javax.swing.JPanel EmployeeCheckoutPanel;
    private javax.swing.JPanel EmployeeCheckoutSelectiohPanel;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JPanel PanelEmployeeCheckout;
    private javax.swing.JButton PowerOffBtn;
    private javax.swing.JButton ProductsBtn;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
