/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Employee;
import model.Product;
import service.CRUDService;
import swing.AdminLogin;

import java.util.List;

/**
 *
 * @author macbookpro
 */
public class EmployeeCheckout extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeCheckout.class.getName());

    /**
     * Creates new form EmployeeCheckout
     */
    public EmployeeCheckout() {
        initComponents();

        CRUDService service = new CRUDService();
        loadProductButtons(service.getAllEntries());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelEmployeeCheckout = new javax.swing.JPanel();
        EmployeeCheckoutSelectiohPanel = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JButton();
        ProductsBtn = new javax.swing.JButton();
        ChangeAccountBtn = new javax.swing.JButton();
        PowerOffBtn = new javax.swing.JButton();
        ProductPanel1 = new javax.swing.JPanel();
        ProductPanel2 = new javax.swing.JPanel();
        ProductPanel3 = new javax.swing.JPanel();
        ProductPanel4 = new javax.swing.JPanel();
        ProductPanel5 = new javax.swing.JPanel();
        ProductPanel6 = new javax.swing.JPanel();
        ProductPanel7 = new javax.swing.JPanel();
        ProductPanel8 = new javax.swing.JPanel();
        ProductPanel9 = new javax.swing.JPanel();
        EmployeeCheckoutPanel = new javax.swing.JPanel();
        CheckoutBtn = new javax.swing.JButton();
        EmployeeCheckoutPanelField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));

        PanelEmployeeCheckout.setBackground(new java.awt.Color(29, 81, 160));

        EmployeeCheckoutSelectiohPanel.setBackground(new java.awt.Color(0, 153, 153));

        HomeBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ProductsBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        ProductsBtn.setText("Products");
        ProductsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        ChangeAccountBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        ChangeAccountBtn.setText("Change Account");
        ChangeAccountBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ChangeAccountBtn.addActionListener(this::ChangeAccountBtnActionPerformed);

        PowerOffBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        PowerOffBtn.setText("Power OFF");
        PowerOffBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout EmployeeCheckoutSelectiohPanelLayout = new javax.swing.GroupLayout(EmployeeCheckoutSelectiohPanel);
        EmployeeCheckoutSelectiohPanel.setLayout(EmployeeCheckoutSelectiohPanelLayout);
        EmployeeCheckoutSelectiohPanelLayout.setHorizontalGroup(
            EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCheckoutSelectiohPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 22, Short.MAX_VALUE))
        );
        EmployeeCheckoutSelectiohPanelLayout.setVerticalGroup(
            EmployeeCheckoutSelectiohPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCheckoutSelectiohPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout ProductPanel1Layout = new javax.swing.GroupLayout(ProductPanel1);
        ProductPanel1.setLayout(ProductPanel1Layout);
        ProductPanel1Layout.setHorizontalGroup(
            ProductPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        ProductPanel1Layout.setVerticalGroup(
            ProductPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel2Layout = new javax.swing.GroupLayout(ProductPanel2);
        ProductPanel2.setLayout(ProductPanel2Layout);
        ProductPanel2Layout.setHorizontalGroup(
            ProductPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        ProductPanel2Layout.setVerticalGroup(
            ProductPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel3Layout = new javax.swing.GroupLayout(ProductPanel3);
        ProductPanel3.setLayout(ProductPanel3Layout);
        ProductPanel3Layout.setHorizontalGroup(
            ProductPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 171, Short.MAX_VALUE)
        );
        ProductPanel3Layout.setVerticalGroup(
            ProductPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 122, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel4Layout = new javax.swing.GroupLayout(ProductPanel4);
        ProductPanel4.setLayout(ProductPanel4Layout);
        ProductPanel4Layout.setHorizontalGroup(
            ProductPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ProductPanel4Layout.setVerticalGroup(
            ProductPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel5Layout = new javax.swing.GroupLayout(ProductPanel5);
        ProductPanel5.setLayout(ProductPanel5Layout);
        ProductPanel5Layout.setHorizontalGroup(
            ProductPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ProductPanel5Layout.setVerticalGroup(
            ProductPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel6Layout = new javax.swing.GroupLayout(ProductPanel6);
        ProductPanel6.setLayout(ProductPanel6Layout);
        ProductPanel6Layout.setHorizontalGroup(
            ProductPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ProductPanel6Layout.setVerticalGroup(
            ProductPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 121, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel7Layout = new javax.swing.GroupLayout(ProductPanel7);
        ProductPanel7.setLayout(ProductPanel7Layout);
        ProductPanel7Layout.setHorizontalGroup(
            ProductPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ProductPanel7Layout.setVerticalGroup(
            ProductPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 111, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel8Layout = new javax.swing.GroupLayout(ProductPanel8);
        ProductPanel8.setLayout(ProductPanel8Layout);
        ProductPanel8Layout.setHorizontalGroup(
            ProductPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ProductPanel8Layout.setVerticalGroup(
            ProductPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ProductPanel9Layout = new javax.swing.GroupLayout(ProductPanel9);
        ProductPanel9.setLayout(ProductPanel9Layout);
        ProductPanel9Layout.setHorizontalGroup(
            ProductPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ProductPanel9Layout.setVerticalGroup(
            ProductPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        EmployeeCheckoutPanel.setBackground(new java.awt.Color(0, 153, 153));
        EmployeeCheckoutPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        CheckoutBtn.setBackground(new java.awt.Color(0, 204, 51));
        CheckoutBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        CheckoutBtn.setText("CHECK OUT");
        CheckoutBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        EmployeeCheckoutPanelField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout EmployeeCheckoutPanelLayout = new javax.swing.GroupLayout(EmployeeCheckoutPanel);
        EmployeeCheckoutPanel.setLayout(EmployeeCheckoutPanelLayout);
        EmployeeCheckoutPanelLayout.setHorizontalGroup(
            EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeCheckoutPanelLayout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addComponent(CheckoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmployeeCheckoutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(EmployeeCheckoutPanelField, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        EmployeeCheckoutPanelLayout.setVerticalGroup(
            EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeCheckoutPanelLayout.createSequentialGroup()
                .addContainerGap(321, Short.MAX_VALUE)
                .addComponent(CheckoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
            .addGroup(EmployeeCheckoutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EmployeeCheckoutPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(EmployeeCheckoutPanelField, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout PanelEmployeeCheckoutLayout = new javax.swing.GroupLayout(PanelEmployeeCheckout);
        PanelEmployeeCheckout.setLayout(PanelEmployeeCheckoutLayout);
        PanelEmployeeCheckoutLayout.setHorizontalGroup(
            PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmployeeCheckoutLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(EmployeeCheckoutSelectiohPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ProductPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ProductPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(EmployeeCheckoutPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelEmployeeCheckoutLayout.setVerticalGroup(
            PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(PanelEmployeeCheckoutLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EmployeeCheckoutPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelEmployeeCheckoutLayout.createSequentialGroup()
                        .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(ProductPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProductPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProductPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ProductPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ProductPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(PanelEmployeeCheckoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProductPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProductPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProductPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(EmployeeCheckoutSelectiohPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEmployeeCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelEmployeeCheckout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ChangeAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeAccountBtnActionPerformed
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangeAccountBtnActionPerformed


    // custom code
    private void loadProductButtons(List<Product> products) {
        javax.swing.JPanel[] panels = {
                ProductPanel1, ProductPanel2, ProductPanel3,
                ProductPanel4, ProductPanel5, ProductPanel6,
                ProductPanel7, ProductPanel8, ProductPanel9
        };

        for (int i = 0; i < panels.length; i++) {
            panels[i].removeAll();
            panels[i].setLayout(new java.awt.BorderLayout());

            if (i < products.size()) {
                final Product product = products.get(i);

                javax.swing.JToggleButton btn = new javax.swing.JToggleButton(
                        "<html><center>" + product.getName() + "</center></html>"
                );

                btn.setBackground(java.awt.Color.WHITE);
                btn.setForeground(java.awt.Color.BLACK);
                btn.setOpaque(true);
                btn.setContentAreaFilled(true);
                btn.setBorderPainted(false);
                btn.setFocusPainted(false);
                btn.setFont(new java.awt.Font("Menlo", java.awt.Font.BOLD, 14));
                btn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                btn.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
                btn.setMargin(new java.awt.Insets(0, 0, 0, 0));

                btn.addActionListener(e -> {
                    if (btn.isSelected()) {
                        btn.setBackground(new java.awt.Color(0, 153, 153));
                        btn.setForeground(java.awt.Color.WHITE);
                        EmployeeCheckoutPanelField.setText(product.getName()); // swap with populateForm(product) later
                        System.out.println("Button pressed");
                    } else {
                        btn.setBackground(java.awt.Color.WHITE);
                        btn.setForeground(java.awt.Color.BLACK);
                        EmployeeCheckoutPanelField.setText("");
                        System.out.println("Button unpressed");
                    }
                });

                panels[i].add(btn, java.awt.BorderLayout.CENTER);

            } else {
                panels[i].setBackground(java.awt.Color.WHITE);
            }

            panels[i].revalidate();
            panels[i].repaint();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeCheckout().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ChangeAccountBtn;
    private javax.swing.JButton CheckoutBtn;
    private javax.swing.JPanel EmployeeCheckoutPanel;
    private javax.swing.JTextField EmployeeCheckoutPanelField;
    private javax.swing.JPanel EmployeeCheckoutSelectiohPanel;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JPanel PanelEmployeeCheckout;
    private javax.swing.JButton PowerOffBtn;
    private javax.swing.JPanel ProductPanel1;
    private javax.swing.JPanel ProductPanel2;
    private javax.swing.JPanel ProductPanel3;
    private javax.swing.JPanel ProductPanel4;
    private javax.swing.JPanel ProductPanel5;
    private javax.swing.JPanel ProductPanel6;
    private javax.swing.JPanel ProductPanel7;
    private javax.swing.JPanel ProductPanel8;
    private javax.swing.JPanel ProductPanel9;
    private javax.swing.JButton ProductsBtn;
    // End of variables declaration//GEN-END:variables
}
