/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package swing.Employee;

import model.receiptbuilder.Receipt;

/**
 *
 * @author cereal
 */
public class ReceiptPopUp extends javax.swing.JDialog {
	
	private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ReceiptPopUp.class.getName());

	/**
	 * Creates new form ReceiptPopUp
	 */
	public ReceiptPopUp(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	// custom code
	public void populate(Receipt receipt) {
		ReceiptDetailTextArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
		ReceiptDetailTextArea.setText(receipt.formatReceipt());
	}


	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                DialogBG = new javax.swing.JPanel();
                ReceiptLabel = new javax.swing.JLabel();
                ReceiptDetailScrollpanel = new javax.swing.JScrollPane();
                ReceiptDetailTextArea = new javax.swing.JTextArea();
                ExitRecieptDialogBtn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                setBackground(new java.awt.Color(0, 153, 153));

                DialogBG.setBackground(new java.awt.Color(0, 153, 153));

                ReceiptLabel.setText("Receipt");

                ReceiptDetailTextArea.setEditable(false);
                ReceiptDetailTextArea.setColumns(20);
                ReceiptDetailTextArea.setRows(5);
                ReceiptDetailTextArea.setWrapStyleWord(true);
                ReceiptDetailScrollpanel.setViewportView(ReceiptDetailTextArea);

                ExitRecieptDialogBtn.setText("Exit");
                ExitRecieptDialogBtn.addActionListener(this::ExitRecieptDialogBtnActionPerformed);

                javax.swing.GroupLayout DialogBGLayout = new javax.swing.GroupLayout(DialogBG);
                DialogBG.setLayout(DialogBGLayout);
                DialogBGLayout.setHorizontalGroup(
                        DialogBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DialogBGLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(DialogBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(DialogBGLayout.createSequentialGroup()
                                                .addComponent(ReceiptDetailScrollpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogBGLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(DialogBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogBGLayout.createSequentialGroup()
                                                                .addComponent(ReceiptLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(162, 162, 162))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DialogBGLayout.createSequentialGroup()
                                                                .addComponent(ExitRecieptDialogBtn)
                                                                .addContainerGap())))))
                );
                DialogBGLayout.setVerticalGroup(
                        DialogBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(DialogBGLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ReceiptLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ReceiptDetailScrollpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ExitRecieptDialogBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 400, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(DialogBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 389, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(DialogBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void ExitRecieptDialogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitRecieptDialogBtnActionPerformed
                // TODO add your handling code here:
		dispose();
        }//GEN-LAST:event_ExitRecieptDialogBtnActionPerformed



	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
			logger.log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			@Override
			public void run() {
				ReceiptPopUp dialog = new ReceiptPopUp(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel DialogBG;
        private javax.swing.JButton ExitRecieptDialogBtn;
        private javax.swing.JScrollPane ReceiptDetailScrollpanel;
        private javax.swing.JTextArea ReceiptDetailTextArea;
        private javax.swing.JLabel ReceiptLabel;
        // End of variables declaration//GEN-END:variables
}
