/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Admin;

/**
 *
 * @author macbookpro
 */
public class AdminDashboard extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminDashboard.class.getName());

    /**
     * Creates new form AdminDashboard
     */
    public AdminDashboard() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                PanelAdminDashboard = new javax.swing.JPanel();
                AddProductBtn = new javax.swing.JButton();
                EditProductBtn = new javax.swing.JButton();
                ReportsBtn = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(0, 102, 255));

                PanelAdminDashboard.setBackground(new java.awt.Color(29, 81, 160));
                PanelAdminDashboard.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

                AddProductBtn.setBackground(new java.awt.Color(78, 176, 238));
                AddProductBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                AddProductBtn.setText("Add Product");
                AddProductBtn.addActionListener(this::AddProductBtnActionPerformed);

                EditProductBtn.setBackground(new java.awt.Color(222, 222, 28));
                EditProductBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                EditProductBtn.setText("Edit Product");
                EditProductBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
                EditProductBtn.addActionListener(this::EditProductBtnActionPerformed);

                ReportsBtn.setBackground(new java.awt.Color(153, 0, 0));
                ReportsBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                ReportsBtn.setText("Reports");
                ReportsBtn.addActionListener(this::ReportsBtnActionPerformed);

                javax.swing.GroupLayout PanelAdminDashboardLayout = new javax.swing.GroupLayout(PanelAdminDashboard);
                PanelAdminDashboard.setLayout(PanelAdminDashboardLayout);
                PanelAdminDashboardLayout.setHorizontalGroup(
                        PanelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAdminDashboardLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(AddProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(EditProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                                .addComponent(ReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                );
                PanelAdminDashboardLayout.setVerticalGroup(
                        PanelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminDashboardLayout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addGroup(PanelAdminDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AddProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EditProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ReportsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(255, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAdminDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAdminDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void AddProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductBtnActionPerformed
        AdminAddProducts add = new AdminAddProducts();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddProductBtnActionPerformed

    private void EditProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditProductBtnActionPerformed
        AdminEditDelete editDelete = new AdminEditDelete();
        editDelete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_EditProductBtnActionPerformed

    private void ReportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportsBtnActionPerformed
        AdminReports reports = new AdminReports();
        reports.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReportsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminDashboard().setVisible(true));
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AddProductBtn;
        private javax.swing.JButton EditProductBtn;
        private javax.swing.JPanel PanelAdminDashboard;
        private javax.swing.JButton ReportsBtn;
        // End of variables declaration//GEN-END:variables
}
