/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Admin;

import model.Product;
import model.Sales;
import service.CRUDService;
import service.checkoutcommand.CheckoutAction;
import service.stockobserver.AdminUI;
import service.stockobserver.Observer;
import swing.AdminLogin;
import swing.Admin.AdminDashboard;

import java.util.List;


/**
 *
 * @author macbookpro
 */
public class AdminReports extends javax.swing.JFrame implements Observer {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminReports.class.getName());

    /**
     * Creates new form AdminReports
     */
    public AdminReports() {
        initComponents();
        checkLowStock();
        showSales();
    }

    // custom code
    // observer design pattern
    @Override
    public void update(String msg) {
        LowStockAlertsTextArea.append(msg + "\n");
    }
    public void checkLowStock() {
        AdminUI adminUI = new AdminUI();
        adminUI.addAlert(this);

        CRUDService service = new CRUDService();
        service.getAllEntries().stream()
                .filter(entry -> entry.getStock() < 5)
                .forEach(entry -> {
                    String msg = String.format("%-10s | %-5d remaining", entry.getName(), (int) entry.getStock());
                    adminUI.notify(msg);
                });
    }

    public void showSales(){
        CRUDService service = new CRUDService();
        Sales sales = Sales.getSalesInstance();

        sales.setUpdatedData(service.getAllEntries());

        for(int i = 0; i < sales.getOriginalData().size(); i++){
            int originalStock = sales.getOriginalData().get(i).getStock();
            int updatedStock = sales.getUpdatedData().get(i).getStock();

            if(updatedStock < originalStock){
                DailySalesReportTextArea.append(String.format("%-10s | Sold: %d\n", sales.getOriginalData().get(i).getName(), (originalStock - updatedStock)));
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                PanelAdminReports = new javax.swing.JPanel();
                ReportsSelectionPanel = new javax.swing.JPanel();
                HomeBtn = new javax.swing.JButton();
                ChangeAccountBtn = new javax.swing.JButton();
                PowerOffBtn = new javax.swing.JButton();
                SalesandStocksPanel = new javax.swing.JPanel();
                DailySalesReportLabel = new javax.swing.JLabel();
                LowStockAlertsLabel = new javax.swing.JLabel();
                jScrollPane2 = new javax.swing.JScrollPane();
                DailySalesReportTextArea = new javax.swing.JTextArea();
                jScrollPane1 = new javax.swing.JScrollPane();
                LowStockAlertsTextArea = new javax.swing.JTextArea();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(204, 204, 204));

                PanelAdminReports.setBackground(new java.awt.Color(29, 81, 160));
                PanelAdminReports.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

                ReportsSelectionPanel.setBackground(new java.awt.Color(0, 153, 153));
                ReportsSelectionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                HomeBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                HomeBtn.setText("Home");
                HomeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                HomeBtn.addActionListener(this::HomeBtnActionPerformed);

                ChangeAccountBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                ChangeAccountBtn.setText("Change Account");
                ChangeAccountBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                ChangeAccountBtn.addActionListener(this::ChangeAccountBtnActionPerformed);

                PowerOffBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                PowerOffBtn.setText("Power OFF");
                PowerOffBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
                PowerOffBtn.addActionListener(this::PowerOffBtnActionPerformed);

                javax.swing.GroupLayout ReportsSelectionPanelLayout = new javax.swing.GroupLayout(ReportsSelectionPanel);
                ReportsSelectionPanel.setLayout(ReportsSelectionPanelLayout);
                ReportsSelectionPanelLayout.setHorizontalGroup(
                        ReportsSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ReportsSelectionPanelLayout.createSequentialGroup()
                                .addGroup(ReportsSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(ReportsSelectionPanelLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addGroup(ReportsSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(ReportsSelectionPanelLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(16, Short.MAX_VALUE))
                );
                ReportsSelectionPanelLayout.setVerticalGroup(
                        ReportsSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ReportsSelectionPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15))
                );

                SalesandStocksPanel.setBackground(new java.awt.Color(0, 153, 153));
                SalesandStocksPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                DailySalesReportLabel.setBackground(new java.awt.Color(255, 255, 255));
                DailySalesReportLabel.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
                DailySalesReportLabel.setForeground(new java.awt.Color(255, 255, 255));
                DailySalesReportLabel.setText("DAILY SALES REPORTS");

                LowStockAlertsLabel.setBackground(new java.awt.Color(255, 255, 255));
                LowStockAlertsLabel.setFont(new java.awt.Font("Menlo", 1, 14)); // NOI18N
                LowStockAlertsLabel.setForeground(new java.awt.Color(255, 255, 255));
                LowStockAlertsLabel.setText("LOW STOCK ALERTS");

                DailySalesReportTextArea.setEditable(false);
                DailySalesReportTextArea.setColumns(20);
                DailySalesReportTextArea.setRows(5);
                DailySalesReportTextArea.setWrapStyleWord(true);
                jScrollPane2.setViewportView(DailySalesReportTextArea);

                LowStockAlertsTextArea.setEditable(false);
                LowStockAlertsTextArea.setColumns(20);
                LowStockAlertsTextArea.setRows(5);
                LowStockAlertsTextArea.setWrapStyleWord(true);
                jScrollPane1.setViewportView(LowStockAlertsTextArea);

                javax.swing.GroupLayout SalesandStocksPanelLayout = new javax.swing.GroupLayout(SalesandStocksPanel);
                SalesandStocksPanel.setLayout(SalesandStocksPanelLayout);
                SalesandStocksPanelLayout.setHorizontalGroup(
                        SalesandStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SalesandStocksPanelLayout.createSequentialGroup()
                                .addGroup(SalesandStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(SalesandStocksPanelLayout.createSequentialGroup()
                                                .addGap(37, 37, 37)
                                                .addComponent(DailySalesReportLabel)
                                                .addGap(27, 27, 27))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SalesandStocksPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(SalesandStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(SalesandStocksPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(LowStockAlertsLabel)
                                                .addGap(63, 63, 63))
                                        .addGroup(SalesandStocksPanelLayout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(7, Short.MAX_VALUE))))
                );
                SalesandStocksPanelLayout.setVerticalGroup(
                        SalesandStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SalesandStocksPanelLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(SalesandStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(LowStockAlertsLabel)
                                        .addComponent(DailySalesReportLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(SalesandStocksPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(20, Short.MAX_VALUE))
                );

                javax.swing.GroupLayout PanelAdminReportsLayout = new javax.swing.GroupLayout(PanelAdminReports);
                PanelAdminReports.setLayout(PanelAdminReportsLayout);
                PanelAdminReportsLayout.setHorizontalGroup(
                        PanelAdminReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAdminReportsLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(ReportsSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SalesandStocksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                );
                PanelAdminReportsLayout.setVerticalGroup(
                        PanelAdminReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminReportsLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(PanelAdminReportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(SalesandStocksPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ReportsSelectionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(335, 335, 335))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAdminReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAdminReports, javax.swing.GroupLayout.PREFERRED_SIZE, 436, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void ChangeAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeAccountBtnActionPerformed
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangeAccountBtnActionPerformed

    private void PowerOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerOffBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PowerOffBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminReports().setVisible(true));
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton ChangeAccountBtn;
        private javax.swing.JLabel DailySalesReportLabel;
        private javax.swing.JTextArea DailySalesReportTextArea;
        private javax.swing.JButton HomeBtn;
        private javax.swing.JLabel LowStockAlertsLabel;
        private javax.swing.JTextArea LowStockAlertsTextArea;
        private javax.swing.JPanel PanelAdminReports;
        private javax.swing.JButton PowerOffBtn;
        private javax.swing.JPanel ReportsSelectionPanel;
        private javax.swing.JPanel SalesandStocksPanel;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;

    // End of variables declaration//GEN-END:variables
}
