/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Admin;

import model.Product;
import service.CRUDService;
import swing.AdminLogin;
import testcode.CrudTest;

import java.util.List;

/**
 *
 * @author macbookpro
 */
public class AdminEditDelete extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminEditDelete.class.getName());

    /**
     * Creates new form AdminEditDelete
     */
    public AdminEditDelete() {
        initComponents();
        loadProducts();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                PanelAdminEditDelete = new javax.swing.JPanel();
                EditDeleteSelectionPanel = new javax.swing.JPanel();
                HomeBtn = new javax.swing.JButton();
                ProductsBtn = new javax.swing.JButton();
                AddProductBtn = new javax.swing.JButton();
                ChangeAccountBtn = new javax.swing.JButton();
                PowerOffBtn = new javax.swing.JButton();
                EditDeletePanel = new javax.swing.JPanel();
                EditBtn = new javax.swing.JButton();
                DeleteBtn = new javax.swing.JButton();
                EditDeleteNamePanel = new javax.swing.JPanel();
                EditDeleteNameText = new javax.swing.JTextField();
                EditDeleteStockPanel = new javax.swing.JPanel();
                EditDeleteStockText = new javax.swing.JTextField();
                EditDeletePricePanel = new javax.swing.JPanel();
                EditDeletePriceText = new javax.swing.JTextField();
                EditDelDescScrollPanel = new javax.swing.JScrollPane();
                EditDeleteDescPanel = new javax.swing.JPanel();
                EditDeleteDescText = new javax.swing.JTextField();
                EditDeleteProductPanel = new javax.swing.JPanel();
                EditDeleteProductLabel = new javax.swing.JLabel();
                EditDelBtn1 = new javax.swing.JButton();
                EdtDelBtn2 = new javax.swing.JButton();
                EditDelBtn3 = new javax.swing.JButton();
                EditDelBtn4 = new javax.swing.JButton();
                EditDelBtn5 = new javax.swing.JButton();
                EditDelBtn6 = new javax.swing.JButton();
                EditDelBtn7 = new javax.swing.JButton();
                EditDelBtn8 = new javax.swing.JButton();
                EditDelBtn9 = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setBackground(new java.awt.Color(204, 204, 204));

                PanelAdminEditDelete.setBackground(new java.awt.Color(29, 81, 160));
                PanelAdminEditDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

                EditDeleteSelectionPanel.setBackground(new java.awt.Color(0, 153, 153));
                EditDeleteSelectionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                HomeBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                HomeBtn.setText("Home");
                HomeBtn.addActionListener(this::HomeBtnActionPerformed);

                ProductsBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                ProductsBtn.setText("Products");

                AddProductBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                AddProductBtn.setText("Add Product");
                AddProductBtn.addActionListener(this::AddProductBtnActionPerformed);

                ChangeAccountBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                ChangeAccountBtn.setText("Change Account");
                ChangeAccountBtn.addActionListener(this::ChangeAccountBtnActionPerformed);

                PowerOffBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                PowerOffBtn.setText("Power OFF");

                javax.swing.GroupLayout EditDeleteSelectionPanelLayout = new javax.swing.GroupLayout(EditDeleteSelectionPanel);
                EditDeleteSelectionPanel.setLayout(EditDeleteSelectionPanelLayout);
                EditDeleteSelectionPanelLayout.setHorizontalGroup(
                        EditDeleteSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EditDeleteSelectionPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(EditDeleteSelectionPanelLayout.createSequentialGroup()
                                .addGroup(EditDeleteSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(EditDeleteSelectionPanelLayout.createSequentialGroup()
                                                .addContainerGap()
                                                .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(EditDeleteSelectionPanelLayout.createSequentialGroup()
                                                .addGroup(EditDeleteSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(EditDeleteSelectionPanelLayout.createSequentialGroup()
                                                                .addGap(34, 34, 34)
                                                                .addGroup(EditDeleteSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(EditDeleteSelectionPanelLayout.createSequentialGroup()
                                                                .addGap(24, 24, 24)
                                                                .addComponent(AddProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 15, Short.MAX_VALUE)))
                                .addContainerGap())
                );
                EditDeleteSelectionPanelLayout.setVerticalGroup(
                        EditDeleteSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EditDeleteSelectionPanelLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(AddProductBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                );

                EditDeletePanel.setBackground(new java.awt.Color(0, 153, 153));
                EditDeletePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                EditBtn.setBackground(new java.awt.Color(222, 222, 28));
                EditBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                EditBtn.setText("Edit");
                EditBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
                EditBtn.addActionListener(this::EditBtnActionPerformed);

                DeleteBtn.setBackground(new java.awt.Color(255, 51, 0));
                DeleteBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
                DeleteBtn.setText("Delete");
                DeleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
                DeleteBtn.addActionListener(this::DeleteBtnActionPerformed);

                EditDeleteNamePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                EditDeleteNameText.setText("Name");
                EditDeleteNameText.addActionListener(this::EditDeleteNameTextActionPerformed);

                javax.swing.GroupLayout EditDeleteNamePanelLayout = new javax.swing.GroupLayout(EditDeleteNamePanel);
                EditDeleteNamePanel.setLayout(EditDeleteNamePanelLayout);
                EditDeleteNamePanelLayout.setHorizontalGroup(
                        EditDeleteNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 209, Short.MAX_VALUE)
                        .addGroup(EditDeleteNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteNamePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeleteNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                EditDeleteNamePanelLayout.setVerticalGroup(
                        EditDeleteNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(EditDeleteNamePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteNamePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeleteNameText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addContainerGap()))
                );

                EditDeleteStockPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                EditDeleteStockText.setText("1");

                javax.swing.GroupLayout EditDeleteStockPanelLayout = new javax.swing.GroupLayout(EditDeleteStockPanel);
                EditDeleteStockPanel.setLayout(EditDeleteStockPanelLayout);
                EditDeleteStockPanelLayout.setHorizontalGroup(
                        EditDeleteStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 91, Short.MAX_VALUE)
                        .addGroup(EditDeleteStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteStockPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeleteStockText, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                EditDeleteStockPanelLayout.setVerticalGroup(
                        EditDeleteStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(EditDeleteStockPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteStockPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeleteStockText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addContainerGap()))
                );

                EditDeletePricePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                EditDeletePriceText.setText("0.0");

                javax.swing.GroupLayout EditDeletePricePanelLayout = new javax.swing.GroupLayout(EditDeletePricePanel);
                EditDeletePricePanel.setLayout(EditDeletePricePanelLayout);
                EditDeletePricePanelLayout.setHorizontalGroup(
                        EditDeletePricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 134, Short.MAX_VALUE)
                        .addGroup(EditDeletePricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeletePricePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeletePriceText, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                EditDeletePricePanelLayout.setVerticalGroup(
                        EditDeletePricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 51, Short.MAX_VALUE)
                        .addGroup(EditDeletePricePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeletePricePanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeletePriceText, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                                        .addContainerGap()))
                );

                EditDelDescScrollPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

                EditDeleteDescText.setText("Desc");

                javax.swing.GroupLayout EditDeleteDescPanelLayout = new javax.swing.GroupLayout(EditDeleteDescPanel);
                EditDeleteDescPanel.setLayout(EditDeleteDescPanelLayout);
                EditDeleteDescPanelLayout.setHorizontalGroup(
                        EditDeleteDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 268, Short.MAX_VALUE)
                        .addGroup(EditDeleteDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteDescPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeleteDescText, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                EditDeleteDescPanelLayout.setVerticalGroup(
                        EditDeleteDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 168, Short.MAX_VALUE)
                        .addGroup(EditDeleteDescPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteDescPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeleteDescText, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                        .addContainerGap()))
                );

                EditDelDescScrollPanel.setViewportView(EditDeleteDescPanel);

                EditDeleteProductLabel.setText("Name");

                javax.swing.GroupLayout EditDeleteProductPanelLayout = new javax.swing.GroupLayout(EditDeleteProductPanel);
                EditDeleteProductPanel.setLayout(EditDeleteProductPanelLayout);
                EditDeleteProductPanelLayout.setHorizontalGroup(
                        EditDeleteProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(EditDeleteProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteProductPanelLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(EditDeleteProductLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                        .addContainerGap()))
                );
                EditDeleteProductPanelLayout.setVerticalGroup(
                        EditDeleteProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 35, Short.MAX_VALUE)
                        .addGroup(EditDeleteProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(EditDeleteProductPanelLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(EditDeleteProductLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                        .addGap(10, 10, 10)))
                );

                javax.swing.GroupLayout EditDeletePanelLayout = new javax.swing.GroupLayout(EditDeletePanel);
                EditDeletePanel.setLayout(EditDeletePanelLayout);
                EditDeletePanelLayout.setHorizontalGroup(
                        EditDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(EditDeletePanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(EditDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(EditDeletePanelLayout.createSequentialGroup()
                                                .addGroup(EditDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(EditDeleteNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EditDeletePricePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(EditDeleteStockPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditDeletePanelLayout.createSequentialGroup()
                                                .addGroup(EditDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(EditDeleteProductPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(EditDelDescScrollPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                                        .addGroup(EditDeletePanelLayout.createSequentialGroup()
                                                                .addGap(0, 0, Short.MAX_VALUE)
                                                                .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(26, 26, 26)
                                                                .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(46, 46, 46))))
                );
                EditDeletePanelLayout.setVerticalGroup(
                        EditDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EditDeletePanelLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(EditDeleteProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(EditDeleteNamePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditDeleteStockPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditDeletePricePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditDelDescScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(EditDeletePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                );

                EditDelBtn6.addActionListener(this::EditDelBtn6ActionPerformed);

                javax.swing.GroupLayout PanelAdminEditDeleteLayout = new javax.swing.GroupLayout(PanelAdminEditDelete);
                PanelAdminEditDelete.setLayout(PanelAdminEditDeleteLayout);
                PanelAdminEditDeleteLayout.setHorizontalGroup(
                        PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAdminEditDeleteLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(EditDeleteSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EditDelBtn4, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addComponent(EditDelBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EditDelBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(EditDelBtn5, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                                        .addComponent(EditDelBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(EdtDelBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(EditDelBtn3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EditDelBtn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EditDelBtn9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(EditDeletePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16))
                );
                PanelAdminEditDeleteLayout.setVerticalGroup(
                        PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(PanelAdminEditDeleteLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelAdminEditDeleteLayout.createSequentialGroup()
                                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(EditDeleteSelectionPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(EditDeletePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(0, 1, Short.MAX_VALUE))
                                        .addGroup(PanelAdminEditDeleteLayout.createSequentialGroup()
                                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(EdtDelBtn2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                                        .addComponent(EditDelBtn3, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                                        .addComponent(EditDelBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(PanelAdminEditDeleteLayout.createSequentialGroup()
                                                                .addGap(51, 51, 51)
                                                                .addComponent(EditDelBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAdminEditDeleteLayout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(EditDelBtn6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(EditDelBtn4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGroup(PanelAdminEditDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(EditDelBtn8, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                                        .addComponent(EditDelBtn9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(EditDelBtn7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addGap(31, 31, 31))))
                );

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAdminEditDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(PanelAdminEditDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void AddProductBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddProductBtnActionPerformed
        AdminAddProducts add = new AdminAddProducts();
        add.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_AddProductBtnActionPerformed

    private void ChangeAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeAccountBtnActionPerformed
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangeAccountBtnActionPerformed

        private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
                // TODO add your handling code here:
        CRUDService service = new CRUDService();

        String originalName = EditDeleteProductLabel.getText().replace("Editing: ", "");
        String newName = EditDeleteNameText.getText();
        int newStock = Integer.parseInt(EditDeleteStockText.getText());
        double newPrice = Double.parseDouble(EditDeletePriceText.getText());
        String newDesc = EditDeleteDescText.getText();

        Product updateProduct = new Product(newName, newStock, newPrice, newDesc);
        service.updateEntry(originalName, updateProduct);

        }//GEN-LAST:event_EditBtnActionPerformed

        private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
                // TODO add your handling code here:
            CRUDService service = new CRUDService();
            String originalName = EditDeleteProductLabel.getText().replace("Editing: ", "");
            service.deleteEntry(originalName);
        }//GEN-LAST:event_DeleteBtnActionPerformed

        private void EditDelBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDelBtn6ActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_EditDelBtn6ActionPerformed

        private void EditDeleteNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDeleteNameTextActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_EditDeleteNameTextActionPerformed

    /**
     * @param args the command line arguments
     */

    // custom code
    private Product[] loadedProducts = new Product[9];

    private void loadProducts() {
        javax.swing.JButton[] productBtns = {
                EditDelBtn1, EdtDelBtn2, EditDelBtn3,
                EditDelBtn4, EditDelBtn5, EditDelBtn6,
                EditDelBtn7, EditDelBtn8, EditDelBtn9
        };

        // Hide all buttons first
        for (javax.swing.JButton btn : productBtns) {
            btn.setVisible(false);
            btn.setText("");
        }

        // Use your existing service layer — no JDBC needed here
        CRUDService service = new CRUDService();
        List<Product> products = service.getAllEntries();

        for (int i = 0; i < products.size() && i < 9; i++) {
            Product p = products.get(i);
            loadedProducts[i] = p;

            productBtns[i].setText(p.getName());
            productBtns[i].setVisible(true);

            final int index = i;
            for (java.awt.event.ActionListener al : productBtns[i].getActionListeners()) {
                productBtns[i].removeActionListener(al);
            }
            productBtns[i].addActionListener(e -> selectProduct(index));
        }
    }
    private void selectProduct(int index) {
        Product p = loadedProducts[index];
        if (p == null) return;

        EditDeleteProductLabel.setText("Editing: " + p.getName());
        EditDeleteNameText.setText(p.getName());
        EditDeleteStockText.setText("Stock: " + p.getStock());
        EditDeletePriceText.setText("Price: ₱" + String.format("%.2f", p.getPrice()));
        EditDeleteDescText.setText("<html>" + p.getDescription() + "</html>");
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminEditDelete().setVisible(true));
    }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton AddProductBtn;
        private javax.swing.JButton ChangeAccountBtn;
        private javax.swing.JButton DeleteBtn;
        private javax.swing.JButton EditBtn;
        private javax.swing.JButton EditDelBtn1;
        private javax.swing.JButton EditDelBtn3;
        private javax.swing.JButton EditDelBtn4;
        private javax.swing.JButton EditDelBtn5;
        private javax.swing.JButton EditDelBtn6;
        private javax.swing.JButton EditDelBtn7;
        private javax.swing.JButton EditDelBtn8;
        private javax.swing.JButton EditDelBtn9;
        private javax.swing.JScrollPane EditDelDescScrollPanel;
        private javax.swing.JPanel EditDeleteDescPanel;
        private javax.swing.JTextField EditDeleteDescText;
        private javax.swing.JPanel EditDeleteNamePanel;
        private javax.swing.JTextField EditDeleteNameText;
        private javax.swing.JPanel EditDeletePanel;
        private javax.swing.JPanel EditDeletePricePanel;
        private javax.swing.JTextField EditDeletePriceText;
        private javax.swing.JLabel EditDeleteProductLabel;
        private javax.swing.JPanel EditDeleteProductPanel;
        private javax.swing.JPanel EditDeleteSelectionPanel;
        private javax.swing.JPanel EditDeleteStockPanel;
        private javax.swing.JTextField EditDeleteStockText;
        private javax.swing.JButton EdtDelBtn2;
        private javax.swing.JButton HomeBtn;
        private javax.swing.JPanel PanelAdminEditDelete;
        private javax.swing.JButton PowerOffBtn;
        private javax.swing.JButton ProductsBtn;
        // End of variables declaration//GEN-END:variables
}
