/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package swing.Admin;
import swing.AdminLogin;
import java.sql.Connection;
import model.Product;
import service.CRUDService;
import database.Database;

/**
 *
 * @author macbookpro
 */
public class AdminAddProducts extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminAddProducts.class.getName());

    /**
     * Creates new form AdminProducts
     */
    public AdminAddProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelAddProducts = new javax.swing.JPanel();
        AddProductPanel = new javax.swing.JPanel();
        AddProductNameField = new javax.swing.JTextField();
        AddProductStockField = new javax.swing.JTextField();
        AddProductPriceField = new javax.swing.JTextField();
        AddProductDescField = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        ResetBtn = new javax.swing.JButton();
        AddProductSelectionPanel = new javax.swing.JPanel();
        HomeBtn = new javax.swing.JButton();
        ProductsBtn = new javax.swing.JButton();
        EditDeleteBtn = new javax.swing.JButton();
        ChangeAccountBtn = new javax.swing.JButton();
        PowerOffBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(29, 81, 160));

        PanelAddProducts.setBackground(new java.awt.Color(29, 81, 160));
        PanelAddProducts.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        AddProductPanel.setBackground(new java.awt.Color(0, 153, 153));
        AddProductPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddProductNameField.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        AddProductNameField.setText("Name");
        AddProductNameField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddProductStockField.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        AddProductStockField.setText("Stock");
        AddProductStockField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddProductPriceField.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        AddProductPriceField.setText("Price");
        AddProductPriceField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddProductDescField.setFont(new java.awt.Font("Menlo", 0, 13)); // NOI18N
        AddProductDescField.setText("Description");
        AddProductDescField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        AddBtn.setBackground(new java.awt.Color(78, 176, 238));
        AddBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        AddBtn.setText("Add");
        AddBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        AddBtn.addActionListener(this::AddBtnActionPerformed);

        ResetBtn.setBackground(new java.awt.Color(255, 153, 0));
        ResetBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        ResetBtn.addActionListener(this::ResetBtnActionPerformed);

        javax.swing.GroupLayout AddProductPanelLayout = new javax.swing.GroupLayout(AddProductPanel);
        AddProductPanel.setLayout(AddProductPanelLayout);
        AddProductPanelLayout.setHorizontalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddProductStockField)
                    .addComponent(AddProductPriceField)
                    .addComponent(AddProductDescField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
                    .addComponent(AddProductNameField, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );
        AddProductPanelLayout.setVerticalGroup(
            AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AddProductNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(AddProductStockField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(AddProductPriceField, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(AddProductPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AddProductDescField, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddProductPanelLayout.createSequentialGroup()
                        .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ResetBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14))
        );

        AddProductSelectionPanel.setBackground(new java.awt.Color(0, 153, 153));
        AddProductSelectionPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        AddProductSelectionPanel.setForeground(new java.awt.Color(255, 255, 255));

        HomeBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        HomeBtn.setText("Home");
        HomeBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        HomeBtn.addActionListener(this::HomeBtnActionPerformed);

        ProductsBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        ProductsBtn.setText("Products");
        ProductsBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        EditDeleteBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        EditDeleteBtn.setText("Edit & Delete Products");
        EditDeleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        EditDeleteBtn.addActionListener(this::EditDeleteBtnActionPerformed);

        ChangeAccountBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        ChangeAccountBtn.setText("Change Account");
        ChangeAccountBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        ChangeAccountBtn.addActionListener(this::ChangeAccountBtnActionPerformed);

        PowerOffBtn.setFont(new java.awt.Font("Menlo", 1, 13)); // NOI18N
        PowerOffBtn.setText("Power OFF");
        PowerOffBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PowerOffBtn.addActionListener(this::PowerOffBtnActionPerformed);

        javax.swing.GroupLayout AddProductSelectionPanelLayout = new javax.swing.GroupLayout(AddProductSelectionPanel);
        AddProductSelectionPanel.setLayout(AddProductSelectionPanelLayout);
        AddProductSelectionPanelLayout.setHorizontalGroup(
            AddProductSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductSelectionPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(AddProductSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(AddProductSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AddProductSelectionPanelLayout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(EditDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        AddProductSelectionPanelLayout.setVerticalGroup(
            AddProductSelectionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddProductSelectionPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProductsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditDeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(ChangeAccountBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PowerOffBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout PanelAddProductsLayout = new javax.swing.GroupLayout(PanelAddProducts);
        PanelAddProducts.setLayout(PanelAddProductsLayout);
        PanelAddProductsLayout.setHorizontalGroup(
            PanelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelAddProductsLayout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(AddProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(PanelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelAddProductsLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(AddProductSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(496, Short.MAX_VALUE)))
        );
        PanelAddProductsLayout.setVerticalGroup(
            PanelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelAddProductsLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(AddProductPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(PanelAddProductsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelAddProductsLayout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(AddProductSelectionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(29, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAddProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelAddProducts, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        AdminDashboard dashboard = new AdminDashboard();
        dashboard.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void EditDeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDeleteBtnActionPerformed
        AdminEditDelete editDelete = new AdminEditDelete();
        editDelete.setVisible((true));
        this.dispose();
    }//GEN-LAST:event_EditDeleteBtnActionPerformed

    private void ChangeAccountBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChangeAccountBtnActionPerformed
        AdminLogin login = new AdminLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ChangeAccountBtnActionPerformed

        private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
                // TODO add your handling code here:
		AddProductNameField.setText("");
		AddProductStockField.setText("");
		AddProductPriceField.setText("");
		AddProductDescField.setText("");
		System.out.println("Product details reset");
        }//GEN-LAST:event_ResetBtnActionPerformed

        private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
                // TODO add your handling code here:
		
//		CrudTest.testAdd();
		
		String name, desc;
		int stock;
		double price;
		
		// get singleton connection
		Database db = Database.getDbInstance();
		Connection conn = db.connect();
		
		// extract field data
		name = AddProductNameField.getText();
		stock = Integer.parseInt(AddProductStockField.getText());
		price = Double.parseDouble(AddProductPriceField.getText());
		desc = AddProductDescField.getText();
		if(desc.isEmpty()){
			desc = " ";
		}
		
		// populate new product instance
		Product product = new Product(name, stock, price, desc);
		
		// add process
		CRUDService service = new CRUDService();
		service.addEntries(product);
		
		
        }//GEN-LAST:event_AddBtnActionPerformed

        private void PowerOffBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PowerOffBtnActionPerformed
                // TODO add your handling code here:
		Database db = Database.getDbInstance();
		db.disconnect();
		System.exit(0);
        }//GEN-LAST:event_PowerOffBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AdminAddProducts().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JTextField AddProductDescField;
    private javax.swing.JTextField AddProductNameField;
    private javax.swing.JPanel AddProductPanel;
    private javax.swing.JTextField AddProductPriceField;
    private javax.swing.JPanel AddProductSelectionPanel;
    private javax.swing.JTextField AddProductStockField;
    private javax.swing.JButton ChangeAccountBtn;
    private javax.swing.JButton EditDeleteBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JPanel PanelAddProducts;
    private javax.swing.JButton PowerOffBtn;
    private javax.swing.JButton ProductsBtn;
    private javax.swing.JButton ResetBtn;
    // End of variables declaration//GEN-END:variables
}
